FROM mysql:5.7

# See https://github.com/docker-library/docs/tree/master/mysql for different setup options

ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=tp
ENV MYSQL_USER=tp_admin
ENV MYSQL_PASSWORD=tp_admin