version: '3'
services:
  mongo:
    image: mongo
    ports:
    - "27018:27018"
    command: mongod --port 27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
